name: Update keymap image

on:
  push:
    paths:
      - 'keymap-drawer/keymap.yml'

jobs:
  draw-keymap:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install keymap-drawer
      run: |
        python -m pip install --upgrade pip
        pip install keymap-drawer

    - name: Run keymap-drawer
      run: |
        mkdir -p images
        keymap draw keymap-drawer/keymap.yml > images/keymap.svg

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update keymap.svg
